### ISSUE TITLE
Banner ads do not work once archived for iOS

### ISSUE THREAD

**Issue by gla5001** [EddyVerbruggen/nativescript-admob#14]
While developing for iOS, the createBanner will work properly both on simulator and devices but as soon as you make an archive and deploy that on a device, the banner ads do not work. This issue has to do with static libraries in GoogleMobileAds i believe. The createBanner just rejects the createBanner promises stating the metadata is found but the kGADAdSizeSmartBannerPortrait  symbol is not found (or what ever other banner size you are using). Is there a work around?

**Comment by EddyVerbruggen** [comment]
Oh bugger..  if you can figure out what the value of the `kGADAdSizeSmartBannerPortrait` actually is you can just use that instead on the line where it now says `kGADAdSizeSmartBannerPortrait`.

This should give you the value when running in debug mode:

```js
console.log("--- runtime value of kGADAdSizeSmartBannerPortrait is: " + kGADAdSizeSmartBannerPortrait);
```

Can you please report it back and/or submit a PR?

**Comment by gla5001** [comment]
So I tried your suggestion of setting the value of ```kGADAdSizeSmartBannerPortrait``` but im not sure what I need to set it to. Doing the console log just prints out <struct [some address]>, which isnt all that useful. Also tried NSStringFromGADAdSize, which just printed out kGADAdSizeSmartBannerPortrait.  I've looked though the GADAdSize.h file and tried setting it to a plain js object with a size and flags property (which didnt work altogether) and setting it using the GADAdSizeFromCGSize function. Using GADAdSizeFromCGSize shows the same behavior as just using the static variable ```kGADAdSizeSmartBannerPortrait``` (works while developing but not in an archive). I also tried the function GADAdSizeFullWidthPortraitWithHeight, but this complained about the symbol not being found at runtime. Im out of ideas to try at the moment.

**Comment by EddyVerbruggen** [comment]
Thanks for your efforts!

The problem here is these symbols are stripped at runtime and in contrast to the Firebase plugin where I encountered the same issue these symbols are not simply Strings, but definitions of the Ad dimensions, so they're much harder to hardcode in your app. I could do that but Google advises not to as those dimensions may change etc.

[This NativeScript/ios-runtime issue](https://github.com/NativeScript/ios-runtime/issues/543) suggests to tell `build.xcconfig` which symbols to _not_ strip for the embedded libraries, so that's what I've done for release 1.3.0 which is now on npm. Please update and check if that helps!

I've also bumped the Podspec to use the latest AdMob release so please make sure to `tns plugin remove nativescript-admob` and `tns plugin add nativescript-admob`, but also `tns platform remove ios` and `tns platform add ios` to clear out any old Pod versions.

**Comment by ignaciolarranaga** [comment]
It is still happening, I have 1.3.0 and just reported a similar problem that end being the same: #19
